<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to the %sWinedatabase%s!'), '<span class="sluisit-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('This is the first version of %sWinedatabase%s.'), '<span class="sluisit-green">', '</span>') ?></p>
    <p><?php echo $this->translate('We are currently working on logging system.') ?></p>
    <p><a class="btn btn-success btn-lg" href="/sayhello" target="_blank"><?php echo $this->translate('Log in') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow the developments') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Winedatabase has just started! If you are interested in the developments follow us on Twitter!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://sluisitconsultancy.nl" target="_blank"><?php echo $this->translate('Developments') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Discover the different modules') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Check the modules, more are to come!'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="http://sluisitconsultancy.nl" target="_blank"><?php echo $this->translate('Check the modules') ?> &raquo;</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Contact') ?></h3>
            </div>
            <div class="panel-body">
                <p><?php echo sprintf($this->translate('Click here if you have questions'), '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
                <p><a class="btn btn-success pull-right" href="/album" target="_blank"><?php echo $this->translate('Ask us') ?> &raquo;</a></p>
          
            </div>
        </div>
    </div>
</div>
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Version Control on Github') ?></h3>
            </div>
            <div class="panel-body">
                 <p><?php echo $this->translate('Check out Github for the latest version of Winedatabase.') ?></p>
                 <p><a class="btn btn-success pull-right" href="https://github.com/gsluis/Wijndatabase" target="_blank"><?php echo $this->translate('Github') ?> &raquo;</a></p>
                            </div>
        </div>
    </div>
</div>